# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc7b5e0134f29d3b0e14304a5fd3fa2cf09daa22ec78a59037cd2691d1403fb361d4ed21a8dd04ee2f94ccaf5ce681c0d19e83df2c39bb74a725c140b59b7d3f

test:
  secret_key_base: 4206ae6b7cb1e751a99243412feee92c6f010eac941d554e04e407094cdd02a70db6fc36a22cda6f4a1858ba9e78b8e1a1bf0ccc62d2bb1e589bf4287d339f6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
